{
 "title": "Microservice — RED",
 "refresh": "15s",
 "panels": [
  {
   "title": "Requetes par seconde (Rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m]))",
     "legendFormat": "Requetes/s"
    }
   ]
  },
  {
   "title": "Taux d'erreur (Errors %)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(http_errors_total[5m]) / rate(http_requests_total[5m]) * 100",
     "legendFormat": "Erreurs %"
    }
   ]
  },
  {
   "title": "Latence p95 (Duration)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le)(rate(http_request_duration_seconds_bucket[5m])))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "Latence p50",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by(le)(rate(http_request_duration_seconds_bucket[5m])))",
     "legendFormat": "p50"
    }
   ]
  }
 ]
}